# business manager system config 企业管理系统配置
bms:
  # 系统名称
  name: 企业管理系统
  # 版本号
  version: 1.0.0
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: char

web:
  # 允许跨域的服务器ip
  allowedOrigins: http://localhost:5173

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.bms.domain.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
